version: '3'
services:
  api:
    build: .
    net: "host"
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    environment:
      PORT: 3000
      MONGO_DB_URL: mongodb://localhost:27017/docker-node
